---
title: "Estimating CWM"
author: "Annegreet Veeken"

output: html_document
---

This script estimates CWM values from the pollen data and from the species measurements

```{r load packages}
library(tidyverse)
library(rjags) 
library(runjags)
library(mcmc)
library(coda)
# library(xlsx)
library(Hmisc) # capitalize function
library(furrr) 
```
# Questions
- use all trait data or per site
- use all flowering/not-flowering

# To do 
- run Plantheight for pollen
- use beta distribution

# Pollen based CWM

## Load data

```{r load gapfilled data, echo=FALSE}
## Species per pollen type list
spec <- readRDS("RDS_files/02_PollenType_species.rds") %>% as_tibble()
spec <- spec %>% 
  distinct(stand.spec, pollentaxon) # remove alternative names

# check for duplicate values (species assigned to two or more pollen type) 
duplicats <- spec %>% 
  filter(duplicated(stand.spec)|
           duplicated(stand.spec, fromLast = TRUE))

## Gap-filled trait data
gapdata <- readRDS("RDS_files/Gap_filled_traits_2020.rds") 
# fix capitalization in  some species names in trait data
gapdata <- gapdata %>% 
  mutate(Species = tolower(Species) %>% capitalize(.))
# fix some species names
spec$stand.spec[spec$stand.spec == "Salix salamonii"] <- 
  "Salix x salamonii"  
spec$stand.spec[spec$stand.spec == "Rabelera holostea"] <- 
  "Stellaria holostea"  
spec$stand.spec[spec$stand.spec == "Doronicum excelsum"] <- 
  "Doronicum plantagineum" 

# check for missing species in the trait data
misspec <- 
  spec$stand.spec[!spec$stand.spec %in% gapdata$Species]
misspec <- tibble(miss.spec = misspec, 
                  note = c("Hybrid", "Not available, but close relative S.fragilus is",
                           "not a species", "Not available", "Not available, garden plant", 
                           "Not available, garden plant", "Not available, garden plant",
                           "Hybrid", "Hybrid","Not available", "Not available, garden plant",
                           "Not available", "Not available","Not available", "Not available",
                           "Not available, garden plant", "Hybrid", "Hybrid","Not available",
                           "Not available"))
# only the relevant species  
gapdata <- gapdata %>% 
  filter(Species %in% spec$stand.spec) 

# merge trait data with spec/pol list
dfTRAIT <- gapdata %>% 
  inner_join(spec, by = c("Species" = "stand.spec")) %>% 
  arrange(pollentaxon) # sort alphabetically

# Pollen data
dfPOL <- readRDS("RDS_files/01_pollen_data_Scot.rds")
pollentaxa <- dfPOL %>% 
  pull(pollentaxon) %>% 
  unique()

traits <- c("PlantHeight", "SLA", "LA", "LeafC", "LeafN", "LDMC")
```

## Normal traits
```{r cmw model log}
dfPOL <- dfPOL %>% 
  ungroup() %>% 
  select(sitename, pollentaxon, percent) %>% 
  # filter out unindentified
  filter(!pollentaxon == "unindentified") %>% 
  pivot_wider(names_from = pollentaxon, values_from = percent) 

cwmlogfunc <- function(selectedtrait){
Trait <- dfTRAIT %>%
  filter(pollentaxon %in% pollentaxa) %>%
  pull(selectedtrait)

Tax <- dfTRAIT %>%
  filter(pollentaxon %in% pollentaxa) %>%
  pull(pollentaxon) %>% 
  as.factor()

N <- length(Trait)

Ab <- dfPOL %>%
  dplyr::select(-sitename) %>%
  as.matrix()
Ntax <- ncol(Ab)
Nsites <- nrow(Ab) 

# for setting priors taxon level
Mean <- mean(Trait)
SD <- sd(Trait)

cat("model {
for (i in 1:Nsites){
cwm[i] ~ dnorm(mean.tax[r[i]], tau.tax[r[i]])
r[i] ~ dcat(Ab[i, 1:Ntax])
}

for (i in 1:N) {
      Trait[i] ~ dlnorm(mean.tax[Tax[i]], tau.tax[Tax[i]])
}

for (l in 1:Ntax){
# vague priors taxon level
    mean.tax[l] ~ dnorm(0, 10^-4)
    tau.tax[l] ~ dgamma(0.001, 0.001)
    sd.tax[l] <- sqrt(1/tau.tax[l])
}

#data# N, Nsites, Trait, Tax, Ntax, Ab
#monitor# cwm
#inits# mean.tax, tau.tax
}", file = "CWMmodel_mix.txt")

# initial values
mean.tax <- list(chain1 = rep(min(Trait),Ntax), chain2 = rep(max(Trait),Ntax))
tau.tax <- list(chain1 = rep(1/(SD*0.1)^2,Ntax), chain2 = rep(1/(SD*10)^2, Ntax))

results <- run.jags("CWMmodel_mix.txt", n.chains = 2)

plot(results, file = paste0("Convergence_diagnostics/Conv_pollen_", selectedtrait,".rds"))

res <- as.matrix(summary(results))
saveRDS(res, 
        paste0("RDS_files/03_CWM_estimates_pollen_", selectedtrait,
               ".rds"))
}

normaltraits <- c("SLA","LA","LeafC","LeafN")
plan(multisession, workers = 2)
furrr::future_map(normaltraits, ~cwmlogfunc(selectedtrait = .))
```

## Beta traits

```{r ldmc all taxa}
Trait <- dfTRAIT %>%
  filter(pollentaxon %in% pollentaxa) %>%
  pull(LDMC)

Tax <- dfTRAIT %>%
  filter(pollentaxon %in% pollentaxa) %>%
  pull(pollentaxon) %>% 
  as.factor()

N <- length(Trait)

Ab <- dfPOL %>%
  dplyr::select(-sitename) %>%
  as.matrix()
Ntax <- ncol(Ab)
Nsites <- nrow(Ab) 

# for setting priors taxon level
Mean <- mean(Trait)
SD <- sd(Trait)

cat("model {
for (i in 1:Nyr){
cwm[i] ~ dbeta(alpha.tax[r[i]], beta.tax[r[i]])
r[i] ~ dcat(Ab[i, 1:Ntax])
}

for (i in 1:N) {
      Trait[i] ~ dbeta(alpha.tax[Tax[i]], beta.tax[Tax[i]])
}
for (l in 1:Ntax){
# vague priors taxon level
    alpha.tax[l] <- mean.tax[l] * sd.tax[l] 
    beta.tax[l] <- (1 - mean.tax[l]) * sd.tax[l]
    mean.tax[l] ~ dnorm(0, 10^-4) 
    sd.tax[l]  ~ dgamma(0.001,0.001)
}

#data# N, Nyr, Trait, Tax, Ntax, Ab
#monitor# cwm
#inits# mean.tax, sd.tax
}", file = "CWMmodel_beta_mix.txt")

# initial values
mean.tax <- list(chain1 = rep(min(Trait),Ntax), chain2 = rep(max(Trait),Ntax))
sd.tax <- list(chain1 = rep(1/(SD*0.1)^2,Ntax), chain2 = rep(1/(SD*10)^2, Ntax))

results <- run.jags("CWMmodel_beta_mix.txt", n.chains = 2)

plot(results, vars = params, file = "Convergence_diagnostics/Conv_pollen_LDMC.pdf")

res <- as.matrix(summary(results))

saveRDS(res, "RDS_files/03_CWM_pollen_LDMC.rds")
```

```{r plant height all taxa}
# Plant height (not in gapfilled data)
TRYdata <- read.csv("Data/24082020TRY_long_cleaned.csv")
TRYdata <- TRYdata %>% filter(AccSpeciesName %in% spec$stand.spec)

TRYdata <- TRYdata %>%
  # convert cm to m
  mutate(StdValue.m = ifelse(UnitName == "cm", StdValue/100, StdValue)) %>% 
  filter(CleanTraitName == "plant_height_generative") %>% 
  # join with pollen list
  left_join(spec, by = c("AccSpeciesName" = "stand.spec"))

Trait <- TRYdata %>%
  filter(pollentaxon %in% pollentaxa) %>%
  pull(StdValue.m)

Tax <- TRYdata %>%
  filter(pollentaxon %in% pollentaxa) %>%
  filter(CleanTraitName == "plant_height_generative") %>%
  pull(pollentaxon) %>% 
  as.factor()

N <- length(Trait)

Ab <- dfPOL %>%
  dplyr::select(-sitename) %>%
  as.matrix()
Ntax <- ncol(Ab)
Nsites <- nrow(Ab) 

# for setting priors taxon level
Mean <- mean(Trait)
SD <- sd(Trait)

# for setting priors taxon level
Mean <- mean(Trait)
SD <- sd(Trait)

# initial values
mean.tax <- list(chain1 = rep(min(Trait),Ntax), chain2 = rep(max(Trait),Ntax))
tau.tax <- list(chain1 = rep(1/(SD*0.1)^2,Ntax), chain2 = rep(1/(SD*10)^2, Ntax))

results <- run.jags("CWMmodel_mix.txt", n.chains = 2)

plot(results, vars = params, file = 
       "Convergence_diag_unbinned_PlantHeight.pdf")

res <- as.matrix(summary(results))

saveRDS(res, "RDS_files/03_CWM_pollen_PlantHeight.rds")
```

# Species based CWM

```{r load data}
# Trait data
plantheight <- readRDS("RDS_files/01_PlantHeight.rds") %>% 
  mutate(sitename = as.factor(sitename), species = as.factor(species)) %>% 
  ungroup()
ldmc <- readRDS("RDS_files/01_LDMC.rds") %>% 
  mutate(sitename = as.factor(sitename), species = as.factor(species)) %>% 
  ungroup()
sla <- readRDS("RDS_files/01_SLA.rds") %>% 
  mutate(sitename = as.factor(sitename), species = as.factor(species)) %>% 
  ungroup()
la <- readRDS("RDS_files/01_LA.rds") %>% 
  mutate(sitename = as.factor(sitename), species = as.factor(species)) %>% 
  ungroup()

lTrait <- list(PlantHeight = plantheight,
               LDMC = ldmc,
               SLA = sla,
               LA = la)

# Species data
dfABUN_a <- readRDS("RDS_files/01_Species_abundance_a.rds")
dfABUN_bc <- readRDS("RDS_files/01_Species_abundance_bc.rds")
```

```{r cwm zone A}
taxa <- dfABUN_a %>% 
  pull(stand.spec) %>% 
  unique()
selectedtrait <- "SLA"

cwm_func <- function(selectedtrait){
# missing trait data
traittax <- lTrait %>%
  pluck(selectedtrait) %>%
  pull(stand.spec) %>% 
  unique
missingtax <- taxa[!taxa %in% traittax] 

# filter species with too little observations (2 or less)
nobs <- lTrait %>%
  pluck(selectedtrait) %>% 
  group_by(stand.spec) %>% 
  summarise(n = n()) %>% 
  filter(n <= 2) %>% 
  pull(stand.spec)

Trait <- lTrait %>%
  pluck(selectedtrait) %>%
  filter(!stand.spec %in% nobs) %>% 
  filter(stand.spec %in% taxa) %>%
  pull(., selectedtrait)

Tax <- lTrait %>%
  pluck(selectedtrait) %>%
  filter(!stand.spec %in% nobs) %>% 
  filter(stand.spec %in% taxa) %>%
  pull(stand.spec) %>% 
  as.factor()

Site <- lTrait %>%
  pluck(selectedtrait) %>%
  filter(!stand.spec %in% nobs) %>% 
  filter(stand.spec %in% taxa) %>%
  pull(sitename) %>% 
  as.factor()

N <- length(Trait)

Ab <- dfABUN_a %>%
  # filter species with missing/too little trait data
  filter(!stand.spec %in% missingtax) %>% 
  filter(!stand.spec %in% nobs) %>% 
  # calculate zone level species abundance
  group_by(sitename, stand.spec) %>% 
  summarise(abun = sum(abun)) %>% 
  group_by(sitename) %>% 
  mutate(specsum = sum(abun, na.rm = TRUE)) %>% 
  group_by(sitename, stand.spec) %>% 
  mutate(abun = abun / specsum * 100) %>% 
  dplyr::select(-specsum) %>% 
  # convert to wide format
  pivot_wider(names_from = stand.spec, values_from = abun,
              values_fill = 0) %>% 
  ungroup() %>% 
  dplyr::select(-sitename) %>%
  as.matrix()

Ntax <- ncol(Ab)
Nsites <- nrow(Ab) 

# for setting priors taxon level
Mean <- mean(Trait)
SD <- sd(Trait)

mod <- "model {
for (siteID in 1:Nsites){
      cwm[siteID] ~ dnorm(mean.tax[siteID,r[siteID]], tau.tax[siteID,r[siteID]])
      r[siteID] ~ dcat(Ab[siteID, 1:Ntax])

for (j in 1:Nsites){
for (i in 1:N) {
    Trait[j,i] ~ dlnorm(mean.tax[Site[j],Tax[i]], tau.tax[Site[j],Tax[i]])
  }
}
for(j in 1:Nsites){
for (taxID in 1:Ntax){
# vague priors taxon level
    mean.tax[j,taxID] ~ dnorm(0, 10^-4)
    tau.tax[j,taxID] ~ dgamma(0.001, 0.001)
  }
} 
}
#data# N, Nsites, Trait, Tax, Ntax, Ab,Site
#monitor# mean.tax, tau.tax, cwm
#inits# mean.tax, tau.tax
}"

# initial values
mean.tax <- list(chain1 = rep(min(Trait), Ntax), 
                 chain2 = rep(max(Trait), Ntax))
tau.tax <- list(chain1 = rep(1/(SD*0.1)^2,Ntax), 
                chain2 = rep(1/(SD*10)^2, Ntax))

results <- run.jags(mod, n.chains = 2)

# plot(results)

res <- as.matrix(summary(results))
saveRDS(res, paste0("RDS_files/03_CWM_estimates_speciesA_", selectedtrait,".rds"))
}

cwm_func(selectedtrait)
# plan(multisession)
# furrr::future_map(c("SLA","LA","PlantHeight","LDMC"),
#                   ~cwm_func(.), .options = furrr_options(seed = TRUE))

```

```{r cwm zone B}
taxa <- dfABUN_bc %>% 
  pull(stand.spec) %>% 
  unique()

cwm_func <- function(selectedtrait){
# missing trait data
traittax <- lTrait %>%
  pluck(selectedtrait) %>%
  pull(stand.spec) %>% 
  unique
missingtax <- taxa[!taxa %in% traittax] 

# filter species with too little observations (2 or less)
nobs <- lTrait %>%
  pluck(selectedtrait) %>% 
  group_by(stand.spec) %>% 
  summarise(n = n()) %>% 
  filter(n <= 2) %>% 
  pull(stand.spec)

Trait <- lTrait %>%
  pluck(selectedtrait) %>%
  filter(!stand.spec %in% nobs) %>% 
  filter(stand.spec %in% taxa) %>%
  pull(selectedtrait)

Tax <- lTrait %>%
  pluck(selectedtrait) %>%
  filter(!stand.spec %in% nobs) %>% 
  filter(stand.spec %in% taxa) %>%
  pull(stand.spec) %>% 
  as.factor()

Site <- lTrait %>%
  pluck(selectedtrait) %>%
  filter(!stand.spec %in% nobs) %>% 
  filter(stand.spec %in% taxa) %>%
  pull(sitename) %>% 
  as.factor()

N <- length(Trait)

Ab <- dfABUN_bc %>% 
  # filter species with missing/too little trait data
  filter(!stand.spec %in% missingtax) %>% 
  filter(!stand.spec %in% nobs) %>% 
  # calculate zone level species abundance
  group_by(sitename, stand.spec) %>% 
  summarise(abun = sum(spec_abun_b)) %>% 
  group_by(sitename) %>% 
  mutate(specsum = sum(abun, na.rm = TRUE)) %>% 
  group_by(sitename, stand.spec) %>% 
  mutate(abun = abun / specsum * 100) %>% 
  select(-specsum) %>% 
  # convert to wide format
  pivot_wider(names_from = stand.spec, values_from = abun,
              values_fill = 0) %>% 
  ungroup() %>% 
  dplyr::select(-sitename) %>%
  as.matrix()

Ntax <- ncol(Ab)
Nsites <- nrow(Ab) 

# for setting priors taxon level
Mean <- mean(Trait)
SD <- sd(Trait)

mod <- "model {
for (siteID in 1:Nsites){
      cwm[siteID] ~ dnorm(mean.tax[r[siteID]], tau.tax[r[siteID]])
      r[siteID] ~ dcat(Ab[siteID, 1:Ntax])
    }

for (i in 1:N) {
      Trait[i] ~ dlnorm(mean.tax[Tax[i]], tau.tax[Tax[i]])
}

for (taxID in 1:Ntax){
# vague priors taxon level
    mean.tax[taxID] ~ dnorm(0, 10^-4)
    tau.tax[taxID] ~ dgamma(0.001, 0.001)
}
    
#data# N, Nsites, Trait, Tax, Ntax, Ab,Site
#monitor# mean.tax, tau.tax, cwm
#inits# mean.tax, tau.tax
}"

# initial values
mean.tax <- list(chain1 = rep(min(Trait), Ntax), 
                 chain2 = rep(max(Trait), Ntax))
tau.tax <- list(chain1 = rep(1/(SD*0.1)^2,Ntax), 
                chain2 = rep(1/(SD*10)^2, Ntax))

results <- run.jags(mod, n.chains = 2)

# plot(results)

res <- as.matrix(summary(results))
saveRDS(res, paste0("RDS_files/03_CWM_estimates_speciesB_",selectedtrait,".rds"))
}

plan(multisession)
furrr::future_map(c("PlantHeight", "SLA", "LDMC", "LA"),
                  ~cwm_func(.), .options = furrr_options(seed = TRUE))

```

```{r cwm zone C}
taxa <- dfABUN_bc %>% 
  pull(stand.spec) %>% 
  unique()

cwm_func <- function(selectedtrait){
# missing trait data
traittax <- lTrait %>%
  pluck(selectedtrait) %>%
  pull(stand.spec) %>% 
  unique
missingtax <- taxa[!taxa %in% traittax] 

# filter species with too little observations (2 or less)
nobs <- lTrait %>%
  pluck(selectedtrait) %>% 
  group_by(stand.spec) %>% 
  summarise(n = n()) %>% 
  filter(n <= 2) %>% 
  pull(stand.spec)

Trait <- lTrait %>%
  pluck(selectedtrait) %>%
  filter(!stand.spec %in% nobs) %>% 
  filter(stand.spec %in% taxa) %>%
  pull(selectedtrait)

Tax <- lTrait %>%
  pluck(selectedtrait) %>%
  filter(!stand.spec %in% nobs) %>% 
  filter(stand.spec %in% taxa) %>%
  pull(stand.spec) %>% 
  as.factor()

Site <- lTrait %>%
  pluck(selectedtrait) %>%
  filter(!stand.spec %in% nobs) %>% 
  filter(stand.spec %in% taxa) %>%
  pull(sitename) %>% 
  as.factor()

N <- length(Trait)

Ab <- dfABUN_bc %>% 
  # filter species with missing/too little trait data
  filter(!stand.spec %in% missingtax) %>% 
  filter(!stand.spec %in% nobs) %>% 
  # calculate zone level species abundance
  group_by(sitename, stand.spec) %>% 
  summarise(abun = sum(spec_abun_c)) %>% 
  group_by(sitename) %>% 
  mutate(specsum = sum(abun, na.rm = TRUE)) %>% 
  group_by(sitename, stand.spec) %>% 
  mutate(abun = abun / specsum * 100) %>% 
  select(-specsum) %>% 
  # convert to wide format
  pivot_wider(names_from = stand.spec, values_from = abun,
              values_fill = 0) %>% 
  ungroup() %>% 
  dplyr::select(-sitename) %>%
  as.matrix()

Ntax <- ncol(Ab)
Nsites <- nrow(Ab) 

# for setting priors taxon level
Mean <- mean(Trait)
SD <- sd(Trait)

mod <- "model {
for (siteID in 1:Nsites){
      cwm[siteID] ~ dnorm(mean.tax[r[siteID]], tau.tax[r[siteID]])
      r[siteID] ~ dcat(Ab[siteID, 1:Ntax])
    }

for (i in 1:N) {
      Trait[i] ~ dlnorm(mean.tax[Tax[i]], tau.tax[Tax[i]])
}

for (taxID in 1:Ntax){
# vague priors taxon level
    mean.tax[taxID] ~ dnorm(0, 10^-4)
    tau.tax[taxID] ~ dgamma(0.001, 0.001)
}
    
#data# N, Nsites, Trait, Tax, Ntax, Ab,Site
#monitor# mean.tax, tau.tax, cwm
#inits# mean.tax, tau.tax
}"

# initial values
mean.tax <- list(chain1 = rep(min(Trait), Ntax), 
                 chain2 = rep(max(Trait), Ntax))
tau.tax <- list(chain1 = rep(1/(SD*0.1)^2,Ntax), 
                chain2 = rep(1/(SD*10)^2, Ntax))

results <- run.jags(mod, n.chains = 2)

# plot(results)

res <- as.matrix(summary(results))
saveRDS(res, paste0("RDS_files/03_CWM_estimates_speciesC_",selectedtrait,".rds"))
}

plan(multisession)
furrr::future_map(c("PlantHeight", "SLA", "LDMC", "LA"),
                  ~cwm_func(.), .options = furrr_options(seed = TRUE))

```

```{r compile estimates}
# all taxa
files <- 
  list.files("RDS_files/") %>% 
  str_subset(pattern = "03_CWM_estimates_")

traitname <- files %>% 
  str_remove(., "03_CWM_estimates_pollen_") %>% 
  str_remove(., "03_CWM_estimates_speciesA_") %>% 
  str_remove(., "03_CWM_estimates_speciesB_") %>% 
  str_remove(., "03_CWM_estimates_speciesC_") %>% 
  str_remove(., ".rds")
traitname
zone <- files %>% 
  str_remove(., "03_CWM_estimates_") %>% 
  str_remove(., "_LA.rds") %>% 
  str_remove(., "_LeafC.rds") %>% 
  str_remove(., "_SLA.rds") %>%
  str_remove(., "_PlantHeight.rds") %>%
  str_remove(., "_LDMC.rds") %>%
  str_remove(., "_LeafN.rds")
zone

lab <- files %>% 
  str_remove(., "03_CWM_estimates_") %>% 
  str_remove(., ".rds")
  
folderpath.fun <- function(x)
{paste("RDS_files/", x, sep = "/")}

dfCWM <- files %>% 
  folderpath.fun(.) %>% 
  purrr::map2(lab, ~readRDS(.) %>% 
               as.data.frame() %>% 
               rownames_to_column("parameter") %>% 
               filter(., str_detect(parameter, "cwm\\[")) %>% 
               dplyr::select(Mean, SD) %>%  
               mutate(label = .y,
                      sitename = seq(1:nrow(.)))) %>% 
  bind_rows() %>% 
  separate(col = label, into = c("zone", "trait"), sep = "_") 

saveRDS(dfCWM,"RDS_files/03_Posterior_CWM.rds")
```


